epoch: 25
hidden_size: 64
input_size: 3
k_qry: 250
k_spt: 250
meta_lr: 1.0e-07
n_way: 2
num_lstm_layers: 2
task_num: 1
update_lr: 1.0e-07
update_step: 250
update_step_test: 5
xcolumns:
- TA_F
- P_F
- lai
- RH
