epoch: 100
hidden_size: 350
batch_size: 256
input_size: 4
meta_lr: 1.0e-03
update_lr: 1.0e-4
num_lstm_layers: 1
max_meta_step: 2
finetune_size: 0.2
encoder_hidden_size: 64
contextcolumns:
xcolumns:
- P_ERA
- LAI
- VPD_ERA
- TA_ERA
- SW_IN_ERA