epoch: 100
hidden_size: 512
batch_size: 16
input_size: 3
meta_lr: 1.0e-03
num_lstm_layers: 1
update_lr: 1.0e-04
max_meta_step: 2
finetune_size: 0.2
encoder_hidden_size: 8
contextcolumns:
xcolumns:
- P_F
- lai
- RH
- SW_IN_POT