epoch: 100
hidden_size: 32
batch_size: 6
input_size: 4
meta_lr: 1.0e-5
update_lr: 1.0e-5
num_lstm_layers: 1
max_meta_step: 1
finetune_size: 0.2
encoder_hidden_size: 8
contextcolumns:
xcolumns:
- Tair
- SW
- RH
- VPD